apiVersion: v1
name: payload
version: 0.0.1
description: Helm chart for all payload components
keywords:
  - payload
sources:
  - http://github.com/payload-app/payload
engine: gotpl
icon: https://istio.io/favicons/android-192x192.png
