version: '2'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    volumes:
     - ./frontend:/usr/src/app/
    ports:
      - 8080:8080
    links:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    volumes:
     - ./backend:/usr/src/app/
    ports:
      - 8081:8081
  status-broadcaster:
    build:
      context: ./status-broadcaster
      dockerfile: Dockerfile.development
    volumes:
     - ./status-broadcaster:/usr/src/app/
    ports:
      - 8082:8082
  webhook-collector:
    build:
      context: ./webhook-collector
      dockerfile: Dockerfile.development
    volumes:
     - ./webhook-collector:/usr/src/app/
    ports:
      - 8083:8083
  queue-service:
    build:
      context: ./queue-service
      dockerfile: Dockerfile.development
    volumes:
     - ./queue-service:/usr/src/app/
    ports:
     - 8084:8084
    links:
     - redis
  redis:
    image: redis
  postgres:
    image: postgres
    volumes:
     - ./postgres:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile.development
    environment:
     - PG_USER=postgres
     - PG_HOST=postgres
     - PG_DATABASE=payload
    volumes:
     - ./user-service:/usr/src/app/
    ports:
     - 8086:8086
    links:
     - postgres
