version: '2'

networks:
  main:
    driver: bridge

services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./proxy:/usr/src/app/
    links:
      - frontend
      - backend
      - github-auth
      - webhook-collector
    networks:
     - main
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    volumes:
     - ./frontend:/usr/src/app/
    networks:
     - main
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    volumes:
     - ./backend:/usr/src/app/
    links:
     - github-service
    networks:
      - main
  status-broadcaster:
    build:
      context: ./status-broadcaster
      dockerfile: Dockerfile.development
    volumes:
     - ./status-broadcaster:/usr/src/app/
    networks:
     - main
  webhook-collector:
    build:
      context: ./webhook-collector
      dockerfile: Dockerfile.development
    volumes:
     - ./webhook-collector:/usr/src/app/
    environment:
     - WORKER_QUEUE=payload-worker
    links:
     - queue-service
     - repo-service
     - user-service
     - organization-service
    networks:
     - main
  github-auth:
    build:
      context: ./github-auth
      dockerfile: Dockerfile.development
    volumes:
     - ./github-auth:/usr/src/app/
    links:
      - user-service
      - session-service
      - github-service
    networks:
     - main
  queue-service:
    build:
      context: ./queue-service
      dockerfile: Dockerfile.development
    volumes:
     - ./queue-service:/usr/src/app/
    links:
     - redis
    networks:
     - main
  redis:
    image: redis
    networks:
     - main
  mongodb:
    image: mongo:latest
    command: mongod --smallfiles
    networks:
     - main
  init-db:
    build:
      context: ./init-db
      dockerfile: Dockerfile.development
    environment:
     - MONGO_URL=mongodb://mongodb:27017
     - MONGO_DB=payload
    volumes:
     - ./init-db:/usr/src/app/
    links:
      - mongodb
    networks:
     - main
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile.development
    networks:
      - main
    environment:
     - MONGO_URL=mongodb://mongodb:27017
     - MONGO_DB=payload
    volumes:
     - ./user-service:/usr/src/app/
    links:
     - mongodb
    networks:
     - main
  session-service:
    build:
      context: ./session-service
      dockerfile: Dockerfile.development
    environment:
     - JWT_SECRET=s3cr3t
    volumes:
     - ./session-service:/usr/src/app/
    networks:
     - main
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.development
    volumes:
     - ./worker:/usr/src/app/
    links:
     - queue-service
     - run-service
    environment:
     - WORKER_QUEUE=payload-worker
     - WORKER_NAME=worker-1
    restart: always
    networks:
     - main
  queue-garbage-collector:
    build:
      context: ./queue-garbage-collector
      dockerfile: Dockerfile.development
    volumes:
     - ./queue-garbage-collector:/usr/src/app/
    links:
     - queue-service
    environment:
     - WORKER_QUEUE=payload-worker
     - SLEEP_AFTER_COLLECT=60 #seconds
    restart: always
    networks:
     - main
  organization-service:
    build:
      context: ./organization-service
      dockerfile: Dockerfile.development
    environment:
     - MONGO_URL=mongodb://mongodb:27017
     - MONGO_DB=payload
    volumes:
     - ./organization-service:/usr/src/app/
    links:
     - mongodb
    networks:
     - main
  github-service:
    build:
      context: ./github-service
      dockerfile: Dockerfile.development
    volumes:
     - ./github-service:/usr/src/app/
    networks:
     - main
  repo-service:
    build:
      context: ./repo-service
      dockerfile: Dockerfile.development
    ports:
    - 3000:3000
    environment:
     - MONGO_URL=mongodb://mongodb:27017
     - MONGO_DB=payload
    volumes:
     - ./repo-service:/usr/src/app/
    links:
     - organization-service
     - user-service
     - mongodb
    networks:
     - main
  run-service:
    build:
      context: ./run-service
      dockerfile: Dockerfile.development
    environment:
     - MONGO_URL=mongodb://mongodb:27017
     - MONGO_DB=payload
    volumes:
     - ./run-service:/usr/src/app/
    links:
     - repo-service
    networks:
     - main
