version: '2'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    volumes:
     - ./frontend:/usr/src/app/
    ports:
      - 3000:3000
    links:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    volumes:
     - ./backend:/usr/src/app/
    expose:
      - 3000
