version: '2'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    volumes:
     - ./frontend:/usr/src/app/
    ports:
      - 8080:8080
    links:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    volumes:
     - ./backend:/usr/src/app/
    ports:
      - 8081:8081
  status-broadcaster:
    build:
      context: ./status-broadcaster
      dockerfile: Dockerfile.development
    volumes:
     - ./status-broadcaster:/usr/src/app/
    ports:
      - 8082:8082
  webhook-collector:
    build:
      context: ./webhook-collector
      dockerfile: Dockerfile.development
    volumes:
     - ./webhook-collector:/usr/src/app/
    ports:
      - 8083:8083
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit-1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "rabbit-1"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbit-1"
