version: '2'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    volumes:
     - ./frontend:/usr/src/app/
    ports:
      - 8080:8080
    links:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    volumes:
     - ./backend:/usr/src/app/
    ports:
      - 8081:8081
  status-broadcaster:
    build:
      context: ./status-broadcaster
      dockerfile: Dockerfile.development
    volumes:
     - ./status-broadcaster:/usr/src/app/
    ports:
      - 8082:8082
  webhook-collector:
    build:
      context: ./webhook-collector
      dockerfile: Dockerfile.development
    volumes:
     - ./webhook-collector:/usr/src/app/
    ports:
      - 8083:8083
  queue-service:
    build:
      context: ./queue-service
      dockerfile: Dockerfile.development
    volumes:
     - ./queue-service:/usr/src/app/
    ports:
     - 8084:8084
    links:
     - redis
  redis:
    image: redis
  datastore:
    image: google/cloud-sdk:latest
    hostname: mydatastore
    expose:
      - 8085
    ports:
      - 8085:8085
    command: gcloud beta emulators datastore start --project=pi-docker --host-port datastore:8085 --no-store-on-disk
