{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "name" . -}}
{{- $servicePort := .Values.service.externalPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- if .Values.istio.enabled}}
    kubernetes.io/ingress.class: "istio"
    {{- end}}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        {{- range .Values.ingress.paths }}
        - path: {{ . }}
          backend:
            serviceName: {{ $serviceName }}
            servicePort: {{ $servicePort }}
        {{- end }}
{{- end -}}
