name: worker
image:
  repository: payloadapp/worker
replicaCount: 1
healthcheck:
  enabled: false
service:
  enabled: false
env:
  # HACK: put placeholder values so WORKER_NAME does not get overwritten
  - name: APP_HOST
    value: ''
  - name: APP_PROTOCOL
    value: ''
  - name: WORKER_QUEUE
    value: ''
  - name: WORKER_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
resources:
  limits:
   cpu: 1000m
   memory: 2000Mi
  requests:
   cpu: 1000m
   memory: 2000Mi
