name: webhook-collector
image:
  repository: payloadapp/webhook-collector
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  paths:
  - /webhook
env:
  - name: APP_HOST
    value: ''
  - name: APP_PROTOCOL
    value: ''
  - name: WORKER_QUEUE
    value: ''
  - name: RETRIES
    value: 3
  - name: LEASE_SECONDS
    value: 30
  - name: MAX_LEASE_SECONDS
    value: 600 # 10 minutes
